version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_DB=django_ecs
      - POSTGRES_USER=parth
      - POSTGRES_PASSWORD=redhat
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0:8000"
    restart: unless-stopped
    container_name: web
    volumes:
      - .:/code
    ports: 
      - "8000:8000"
      - "80:80"
    depends_on:
      - db
    networks:
      - mynetwork

volumes: 
  postgres-data:
  esdata:
    driver: local

networks:
  mynetwork:
    driver: bridge